Quality Score = AVERAGE('Quality Summary'[quality_score])
Rows Received = SUM('Quality Summary'[rows_received])
Rows Accepted = SUM('Quality Summary'[rows_accepted])
Rows Rejected = SUM('Quality Summary'[rows_rejected])
Rejection Rate = DIVIDE([Rows Rejected], [Rows Received])
Latest Metric Value = CALCULATE(MAX('Metric Monitoring'[value]), LASTDATE('Calendar'[Date]))
Previous Metric Value = CALCULATE([Latest Metric Value], DATEADD('Calendar'[Date], -1, MONTH))
Metric MoM % = DIVIDE([Latest Metric Value] - [Previous Metric Value], [Previous Metric Value])
Budget Variance % = DIVIDE(SUM('Metric Monitoring'[value]) - SUM('Metric Monitoring'[budget]), SUM('Metric Monitoring'[budget]))
Open Anomalies = CALCULATE(COUNTROWS('Anomaly Center'), 'Anomaly Center'[review_status] = "open")
Critical Anomalies = CALCULATE([Open Anomalies], 'Anomaly Center'[severity] = "critical")
Completed Runs = CALCULATE(COUNTROWS('Control Center'), 'Control Center'[status] = "completed")
Average Processing Seconds = DIVIDE(AVERAGE('Control Center'[processing_time_ms]), 1000)

